apiVersion: 1

deleteDatasources:
  - name: TrenchPostgres
    orgId: 1

datasources:
  - name: TrenchPostgres
    type: postgres
    access: proxy
    isDefault: true
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: TRENCH123
    jsonData:
      database: postgres
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
